name: umswc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - docopt=0.6.2
  - pip=19.2.1
  - pygithub=1.43.6
  - python=3.7.3
  - pyyaml=5.1.1
  - readline=8.0
  - requests=2.22.0
  - setuptools=41.0.1
  - yaml=0.1.7

