name: auto-update

on:
- push

jobs:
  update:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: umswc
           environment-file: environment.yml
           python-version: 3.7
           auto-activate-base: false
      - name: Update
        shell: bash -l {0}
        run: |
          python update-workshops.py --token ${{ secrets.GITHUB_TOKEN }}
          git status
          git add .
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
          git diff-index --quiet HEAD \
          || git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '🛠 Auto-update workshops page'
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}